services:
  # --- Redis Master ---
  redis-master:
    image: redis:7.0
    container_name: redis-master
    command: redis-server
    ports:
      - "6379:6379"

  # --- Redis Slaves ---
  redis-slave:
    image: redis:7.0
    container_name: redis-slave
    command: redis-server --replicaof redis-master 6379
    ports:
      - "6380:6379"
    depends_on:
      - redis-master

  # --- Redis Sentinels ---
  redis-sentinel:
    image: redis:7.0
    container_name: redis-sentinel
    command: >
      sh -c "cp /etc/redis/sentinel-template.conf /data/sentinel.conf && 
             chmod 777 /data/sentinel.conf && 
             redis-sentinel /data/sentinel.conf"
    ports:
      - "26379:26379"
    volumes:
      - ./sentinel/sentinel-template.conf:/etc/redis/sentinel-template.conf:ro
    depends_on:
      - redis-master
      - redis-slave
