services:
  # --- Redis Master ---
  master:
    image: redis:8.6.0
    container_name: wormhole-redis-master
    command: redis-server
    ports:
      - "6379:6379"
  # --- Redis Slaves ---
  slave:
    image: redis:8.6.0
    container_name: wormhole-redis-slave
    command: redis-server --replicaof wormhole-redis-master 6379
    ports:
      - "16379:6379"
    depends_on:
      - master
  # --- Redis Sentinels ---
  sentinel:
    image: redis:8.6.0
    container_name: wormhole-redis-sentinel
    command: |
      sh -c "cp /etc/redis/sentinel-template.conf /data/sentinel.conf && \
      chmod 777 /data/sentinel.conf && \
      redis-sentinel /data/sentinel.conf"
    ports:
      - "26379:26379"
    volumes:
      - ./sentinel/sentinel-template.conf:/etc/redis/sentinel-template.conf:ro
    depends_on:
      - master
      - slave
