[package]
name = "wormhole-gateway"
version.workspace = true
edition.workspace = true

[dependencies]
tokio = { workspace = true }
# tracing
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
