[package]
name = "wormhole-gateway"
version.workspace = true
edition.workspace = true

[dependencies]
# workspace members
wormhole-core = { workspace = true }
wormhole-shortener = { workspace = true }
wormhole-redirector = { workspace = true }
tokio = { workspace = true }
# tracing
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
axum = { version = "0.8.4" }
serde = { workspace = true, features = ["derive"] }
tower = { version = "0.5", features = ["util"] }
jiff = { workspace = true }
typed-builder = { workspace = true }
async-trait = { workspace = true }
