[package]
name = "wormhole-proto-schema"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
# gRPC
tonic = { workspace = true }

[build-dependencies]
tonic-prost-build = { workspace = true }
