[package]
name = "wormhole-generator"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
# workspace members
wormhole-core = { workspace = true }
wormhole-tinyflake = { workspace = true }

[dev-dependencies]
jiff = { workspace = true }
